// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.33.1
// source: codec/protobuf/internal/testpb/testevent.proto

package testpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TestProductCreated struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductName   string                 `protobuf:"bytes,1,opt,name=product_name,json=productName,proto3" json:"product_name,omitempty"`
	Price         int64                  `protobuf:"varint,2,opt,name=price,proto3" json:"price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestProductCreated) Reset() {
	*x = TestProductCreated{}
	mi := &file_codec_protobuf_internal_testpb_testevent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestProductCreated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestProductCreated) ProtoMessage() {}

func (x *TestProductCreated) ProtoReflect() protoreflect.Message {
	mi := &file_codec_protobuf_internal_testpb_testevent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestProductCreated.ProtoReflect.Descriptor instead.
func (*TestProductCreated) Descriptor() ([]byte, []int) {
	return file_codec_protobuf_internal_testpb_testevent_proto_rawDescGZIP(), []int{0}
}

func (x *TestProductCreated) GetProductName() string {
	if x != nil {
		return x.ProductName
	}
	return ""
}

func (x *TestProductCreated) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

var File_codec_protobuf_internal_testpb_testevent_proto protoreflect.FileDescriptor

const file_codec_protobuf_internal_testpb_testevent_proto_rawDesc = "" +
	"\n" +
	".codec/protobuf/internal/testpb/testevent.proto\x12\x1aflux.codec.protobuf.testpb\"M\n" +
	"\x12TestProductCreated\x12!\n" +
	"\fproduct_name\x18\x01 \x01(\tR\vproductName\x12\x14\n" +
	"\x05price\x18\x02 \x01(\x03R\x05priceB6Z4github.com/wotek/flux/codec/protobuf/internal/testpbb\x06proto3"

var (
	file_codec_protobuf_internal_testpb_testevent_proto_rawDescOnce sync.Once
	file_codec_protobuf_internal_testpb_testevent_proto_rawDescData []byte
)

func file_codec_protobuf_internal_testpb_testevent_proto_rawDescGZIP() []byte {
	file_codec_protobuf_internal_testpb_testevent_proto_rawDescOnce.Do(func() {
		file_codec_protobuf_internal_testpb_testevent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_codec_protobuf_internal_testpb_testevent_proto_rawDesc), len(file_codec_protobuf_internal_testpb_testevent_proto_rawDesc)))
	})
	return file_codec_protobuf_internal_testpb_testevent_proto_rawDescData
}

var file_codec_protobuf_internal_testpb_testevent_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_codec_protobuf_internal_testpb_testevent_proto_goTypes = []any{
	(*TestProductCreated)(nil), // 0: flux.codec.protobuf.testpb.TestProductCreated
}
var file_codec_protobuf_internal_testpb_testevent_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_codec_protobuf_internal_testpb_testevent_proto_init() }
func file_codec_protobuf_internal_testpb_testevent_proto_init() {
	if File_codec_protobuf_internal_testpb_testevent_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_codec_protobuf_internal_testpb_testevent_proto_rawDesc), len(file_codec_protobuf_internal_testpb_testevent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_codec_protobuf_internal_testpb_testevent_proto_goTypes,
		DependencyIndexes: file_codec_protobuf_internal_testpb_testevent_proto_depIdxs,
		MessageInfos:      file_codec_protobuf_internal_testpb_testevent_proto_msgTypes,
	}.Build()
	File_codec_protobuf_internal_testpb_testevent_proto = out.File
	file_codec_protobuf_internal_testpb_testevent_proto_goTypes = nil
	file_codec_protobuf_internal_testpb_testevent_proto_depIdxs = nil
}
