// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.33.1
// source: codec/protobuf/envelope.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EnvelopeDTO struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	EventName      string                 `protobuf:"bytes,2,opt,name=event_name,json=eventName,proto3" json:"event_name,omitempty"`
	EventPayload   []byte                 `protobuf:"bytes,3,opt,name=event_payload,json=eventPayload,proto3" json:"event_payload,omitempty"`
	Revision       uint64                 `protobuf:"varint,4,opt,name=revision,proto3" json:"revision,omitempty"`
	GlobalPosition uint64                 `protobuf:"varint,5,opt,name=global_position,json=globalPosition,proto3" json:"global_position,omitempty"`
	Actor          string                 `protobuf:"bytes,6,opt,name=actor,proto3" json:"actor,omitempty"`
	StreamId       string                 `protobuf:"bytes,7,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	CorrelationId  string                 `protobuf:"bytes,8,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Metadata       map[string]string      `protobuf:"bytes,10,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	CausationId    string                 `protobuf:"bytes,11,opt,name=causation_id,json=causationId,proto3" json:"causation_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *EnvelopeDTO) Reset() {
	*x = EnvelopeDTO{}
	mi := &file_codec_protobuf_envelope_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnvelopeDTO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnvelopeDTO) ProtoMessage() {}

func (x *EnvelopeDTO) ProtoReflect() protoreflect.Message {
	mi := &file_codec_protobuf_envelope_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnvelopeDTO.ProtoReflect.Descriptor instead.
func (*EnvelopeDTO) Descriptor() ([]byte, []int) {
	return file_codec_protobuf_envelope_proto_rawDescGZIP(), []int{0}
}

func (x *EnvelopeDTO) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *EnvelopeDTO) GetEventName() string {
	if x != nil {
		return x.EventName
	}
	return ""
}

func (x *EnvelopeDTO) GetEventPayload() []byte {
	if x != nil {
		return x.EventPayload
	}
	return nil
}

func (x *EnvelopeDTO) GetRevision() uint64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

func (x *EnvelopeDTO) GetGlobalPosition() uint64 {
	if x != nil {
		return x.GlobalPosition
	}
	return 0
}

func (x *EnvelopeDTO) GetActor() string {
	if x != nil {
		return x.Actor
	}
	return ""
}

func (x *EnvelopeDTO) GetStreamId() string {
	if x != nil {
		return x.StreamId
	}
	return ""
}

func (x *EnvelopeDTO) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *EnvelopeDTO) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *EnvelopeDTO) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *EnvelopeDTO) GetCausationId() string {
	if x != nil {
		return x.CausationId
	}
	return ""
}

var File_codec_protobuf_envelope_proto protoreflect.FileDescriptor

const file_codec_protobuf_envelope_proto_rawDesc = "" +
	"\n" +
	"\x1dcodec/protobuf/envelope.proto\x12\x13flux.codec.protobuf\x1a\x1fgoogle/protobuf/timestamp.proto\"\xe7\x03\n" +
	"\vEnvelopeDTO\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"event_name\x18\x02 \x01(\tR\teventName\x12#\n" +
	"\revent_payload\x18\x03 \x01(\fR\feventPayload\x12\x1a\n" +
	"\brevision\x18\x04 \x01(\x04R\brevision\x12'\n" +
	"\x0fglobal_position\x18\x05 \x01(\x04R\x0eglobalPosition\x12\x14\n" +
	"\x05actor\x18\x06 \x01(\tR\x05actor\x12\x1b\n" +
	"\tstream_id\x18\a \x01(\tR\bstreamId\x12%\n" +
	"\x0ecorrelation_id\x18\b \x01(\tR\rcorrelationId\x129\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12J\n" +
	"\bmetadata\x18\n" +
	" \x03(\v2..flux.codec.protobuf.EnvelopeDTO.MetadataEntryR\bmetadata\x12!\n" +
	"\fcausation_id\x18\v \x01(\tR\vcausationId\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B&Z$github.com/wotek/flux/codec/protobufb\x06proto3"

var (
	file_codec_protobuf_envelope_proto_rawDescOnce sync.Once
	file_codec_protobuf_envelope_proto_rawDescData []byte
)

func file_codec_protobuf_envelope_proto_rawDescGZIP() []byte {
	file_codec_protobuf_envelope_proto_rawDescOnce.Do(func() {
		file_codec_protobuf_envelope_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_codec_protobuf_envelope_proto_rawDesc), len(file_codec_protobuf_envelope_proto_rawDesc)))
	})
	return file_codec_protobuf_envelope_proto_rawDescData
}

var file_codec_protobuf_envelope_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_codec_protobuf_envelope_proto_goTypes = []any{
	(*EnvelopeDTO)(nil),           // 0: flux.codec.protobuf.EnvelopeDTO
	nil,                           // 1: flux.codec.protobuf.EnvelopeDTO.MetadataEntry
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
}
var file_codec_protobuf_envelope_proto_depIdxs = []int32{
	2, // 0: flux.codec.protobuf.EnvelopeDTO.created_at:type_name -> google.protobuf.Timestamp
	1, // 1: flux.codec.protobuf.EnvelopeDTO.metadata:type_name -> flux.codec.protobuf.EnvelopeDTO.MetadataEntry
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_codec_protobuf_envelope_proto_init() }
func file_codec_protobuf_envelope_proto_init() {
	if File_codec_protobuf_envelope_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_codec_protobuf_envelope_proto_rawDesc), len(file_codec_protobuf_envelope_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_codec_protobuf_envelope_proto_goTypes,
		DependencyIndexes: file_codec_protobuf_envelope_proto_depIdxs,
		MessageInfos:      file_codec_protobuf_envelope_proto_msgTypes,
	}.Build()
	File_codec_protobuf_envelope_proto = out.File
	file_codec_protobuf_envelope_proto_goTypes = nil
	file_codec_protobuf_envelope_proto_depIdxs = nil
}
